"""
We follow panoptic lifting classes mapping
"""



stuff2std = {
    'person': None, 
    'bicycle': None, 
    'car': None, 
    'motorcycle': None, 
    'airplane': None, 
    'bus': None, 
    'train': None, 
    'truck': None, 
    'boat': None, 
    'traffic light': None, 
    'fire hydrant': None, 
    'stop sign': None, 
    'parking meter': None, 
    'bench': 'sofa', 
    'bird': None, 
    'cat': None, 
    'dog': None, 
    'horse': None, 
    'sheep': None, 
    'cow': None, 
    'elephant': None, 
    'bear': None, 
    'zebra': None, 
    'giraffe': None, 
    'backpack': 'bag', 
    'umbrella': None, 
    'handbag': 'bag', 
    'tie': None, 
    'suitcase': None, 
    'frisbee': None, 
    'skis': None, 
    'snowboard': None, 
    'sports ball': None, 
    'kite': None, 
    'baseball bat': None, 
    'baseball glove': None, 
    'skateboard': None, 
    'surfboard': None, 
    'tennis racket': None, 
    'bottle': None, 
    'wine glass': None, 
    'cup': None, 
    'fork': None, 
    'knife': None, 
    'spoon': None, 
    'bowl': None, 
    'banana': None, 
    'apple': None, 
    'sandwich': None, 
    'orange': None, 
    'broccoli': None, 
    'carrot': None, 
    'hot dog': None, 
    'pizza': None, 
    'donut': None, 
    'cake': None, 
    'chair': 'chair', 
    'couch': 'sofa', 
    'potted plant': 'plant', 
    'bed': 'bed', 
    'dining table': 'table', 
    'toilet': 'toilet', 
    'tv': 'tv', 
    'laptop': 'laptop', 
    'mouse': 'mouse', 
    'remote': None, 
    'keyboard': 'keyboard', 
    'cell phone': None, 
    'microwave': 'microwave', 
    'oven': 'oven', 
    'toaster': 'toaster', 
    'sink': 'sink', 
    'refrigerator': 'refrigerator', 
    'book': None, 
    'clock': 'clock', 
    'vase': 'vase', 
    'scissors': None, 
    'teddy bear': None, 
    'hair drier': None, 
    'toothbrush': None, 
    'banner': None, 
    'blanket': None, 
    'bridge': None, 
    'cardboard': None, 
    'counter': 'counter', 
    'curtain': 'curtain', 
    'door-stuff': 'door', 
    'floor-wood': 'floor', 
    'flower': 'plant', 
    'fruit': None, 
    'gravel': None, 
    'house': None, 
    'light': 'light', 
    'mirror-stuff': 'mirror', 
    'net': None, 
    'pillow': 'pillow', 
    'platform': None, 
    'playingfield': None, 
    'railroad': None, 
    'river': None, 
    'road': None, 
    'roof': None, 
    'sand': None, 
    'sea': None, 
    'shelf': 'shelves', 
    'snow': None, 
    'stairs': 'stairs', 
    'tent': None, 
    'towel': 'towel', 
    'wall-brick': 'wall', 
    'wall-stone': 'wall', 
    'wall-tile': 'wall', 
    'wall-wood': 'wall', 
    'water-other': 'wall', 
    'window-blind': 'window', 
    'window-other': 'window', 
    'tree-merged': 'plant', 
    'fence-merged': 'fence', 
    'ceiling-merged': 'ceiling', 
    'sky-other-merged': None, 
    'cabinet-merged': 'cabinet', 
    'table-merged': 'table', 
    'floor-other-merged': 'floor', 
    'pavement-merged': None, 
    'mountain-merged': None, 
    'grass-merged': None, 
    'dirt-merged': None, 
    'paper-merged': None, 
    'food-other-merged': None, 
    'building-other-merged': None, 
    'rock-merged': None, 
    'wall-other-merged': 'wall', 
    'rug-merged': 'floor'
}

thing2std = {
    'person': None, 
    'bicycle': None, 
    'car': None, 
    'motorcycle': None, 
    'airplane': None, 
    'bus': None, 
    'train': None, 
    'truck': None, 
    'boat': None, 
    'traffic light': None, 
    'fire hydrant': None, 
    'stop sign': None, 
    'parking meter': None, 
    'bench': 'sofa', 
    'bird': None, 
    'cat': None, 
    'dog': None, 
    'horse': None, 
    'sheep': None, 
    'cow': None, 
    'elephant': None, 
    'bear': None, 
    'zebra': None, 
    'giraffe': None, 
    'backpack': 'bag', 
    'umbrella': None, 
    'handbag': 'bag', 
    'tie': None, 
    'suitcase': None, 
    'frisbee': None, 
    'skis': None, 
    'snowboard': None, 
    'sports ball': None, 
    'kite': None, 
    'baseball bat': None, 
    'baseball glove': None, 
    'skateboard': None, 
    'surfboard': None, 
    'tennis racket': None, 
    'bottle': None, 
    'wine glass': None, 
    'cup': None, 
    'fork': None, 
    'knife': None, 
    'spoon': None, 
    'bowl': None, 
    'banana': None, 
    'apple': None, 
    'sandwich': None, 
    'orange': None, 
    'broccoli': None, 
    'carrot': None, 
    'hot dog': None, 
    'pizza': None, 
    'donut': None, 
    'cake': None, 
    'chair': 'chair', 
    'couch': 'sofa',
    'potted plant': 'plant', 
    'bed': 'bed', 
    'dining table': 'table', 
    'toilet': 'toilet', 
    'tv': 'tv', 
    'laptop': 'laptop', 
    'mouse': 'mouse', 
    'remote': None, 
    'keyboard': 'keyboard', 
    'cell phone': None, 
    'microwave': 'microwave', 
    'oven': 'oven', 
    'toaster': 'toaster', 
    'sink': 'sink', 
    'refrigerator': 'refrigerator', 
    'book': None, 
    'clock': 'clock', 
    'vase': 'vase', 
    'scissors': None, 
    'teddy bear': None, 
    'hair drier': None, 
    'toothbrush': None

}

std_labels = set(list(stuff2std.values()) + list(thing2std.values()))
std_labels.remove(None)
std_labels = ['none'] + list(sorted(std_labels))

print("Load ", len(std_labels), " labels as standard label")

print(std_labels)

# from mask2former import add_maskformer2_config
# from detectron2.projects.deeplab import add_deeplab_config
# from detectron2.config import get_cfg
# from detectron2.data import MetadataCatalog

# def setup_cfg(config_file):
#     # load config from file and command-line arguments
#     cfg = get_cfg()
#     add_deeplab_config(cfg)
#     add_maskformer2_config(cfg)
#     cfg.merge_from_file(config_file)
#     cfg.freeze()
#     return cfg


# config_file = './configs/coco/panoptic-segmentation/swin/maskformer2_swin_large_IN21k_384_bs16_100ep.yaml'
# cfg = setup_cfg(config_file)

# metadata = MetadataCatalog.get(
#             cfg.DATASETS.TEST[0] if len(cfg.DATASETS.TEST) else "__unused"
#         )

# import ipdb;ipdb.set_trace() # breakpoint 23

# print()