# wordnet mapping to map cat
from nltk.corpus import wordnet as wn

cat2synset = {
    'chair': wn.synset('chair.n.01'), 
    'table': wn.synset('table.n.02'), 
    'picture': wn.synset('picture.n.02'), 
    'cabinet': wn.synset('cabinet.n.01'),            
    'cushion': wn.synset('cushion.n.03'),
    'sofa': wn.synset('sofa.n.01'),
    'bed': wn.synset('bed.n.01'),
    'chest_of_drawers': wn.synset('chest_of_drawers.n.01'),       
    'plant': wn.synset('plant.n.02'),        
    'sink': wn.synset('sink.n.01'), 
    'toilet': wn.synset('toilet.n.02'), 
    'stool': wn.synset('stool.n.01'),
    'towel': wn.synset('towel.n.01'),             
    'tv_monitor': wn.synset('television.n.01'), 
    'shower': wn.synset('shower.n.01'),     
    'bathtub': wn.synset('bathtub.n.01'), 
    'counter': wn.synset('counter.n.01'),             
    'fireplace': wn.synset('fireplace.n.01'), 
    'gym_equipment': wn.synset('sports_equipment.n.01'), 
    'seating':wn.synset('seat.n.03'), 
    'clothes': wn.synset('clothes.n.01'),
    'appliances': wn.synset('appliance.n.02'),
    'door': wn.synset('door.n.02'),
    'mirror': wn.synset('mirror.n.01'),
    'window': wn.synset('window.n.01'),
    'stairs': wn.synset('stair.n.01'),
    'shelving': wn.synset('shelf.n.01'),

    # noisy sem map labele
    'refrigerator': wn.synset('refrigerator.n.01'),
    'bag': wn.synset('bag.n.01'),
    'clock': wn.synset('clock.n.01'),
    'curtain': wn.synset('curtain.n.01'),
    'fence': wn.synset('fence.n.01'),
    'keyboard': wn.synset('keyboard.n.01'),
    'laptop': wn.synset('laptop.n.01'),
    'light': wn.synset('light.n.02'),
    'microwave': wn.synset('microwave.n.02'),
    'mouse': wn.synset('mouse.n.04'),
    'oven': wn.synset('oven.n.01'),
    'pillow': wn.synset('pillow.n.01'),
    'toaster': wn.synset('toaster.n.01'),
    'vase':  wn.synset('vase.n.01'), 
    'wall':  wn.synset('wall.n.01'), 

}

cat2synset_built_sem={
    'door': wn.synset('door.n.02'),
    'mirror': wn.synset('mirror.n.01'),
    'window': wn.synset('window.n.01'),
    'stairs': wn.synset('stair.n.01'),
    'shelving': wn.synset('shelf.n.01'),
    'refrigerator': wn.synset('refrigerator.n.01'),
    'bag': wn.synset('bag.n.01'),
    'clock': wn.synset('clock.n.01'),
    'curtain': wn.synset('curtain.n.01'),
    'fence': wn.synset('fence.n.01'),
    'keyboard': wn.synset('keyboard.n.01'),
    'laptop': wn.synset('laptop.n.01'),
    'light': wn.synset('light.n.02'),
    'microwave': wn.synset('microwave.n.02'),
    'mouse': wn.synset('mouse.n.04'),
    'oven': wn.synset('oven.n.01'),
    'pillow': wn.synset('pillow.n.01'),
    'toaster': wn.synset('toaster.n.01'),
    'vase':  wn.synset('vase.n.01'), 
    'wall':  wn.synset('wall.n.01'), 
    'counter': wn.synset('counter.n.01'), 
    'towel': wn.synset('towel.n.01'),             
    'tv_monitor': wn.synset('television.n.01'), 
    'sink': wn.synset('sink.n.01'), 
    'toilet': wn.synset('toilet.n.02'), 
    'sofa': wn.synset('sofa.n.01'),
    'bed': wn.synset('bed.n.01'),
    'cabinet': wn.synset('cabinet.n.01'),  
    'chair': wn.synset('chair.n.01'), 
    'table': wn.synset('table.n.02'), 
}

word_mapping_built_sem={
    'television': 'tv_monitor',
    'tv': 'tv_monitor',
    'couch': 'sofa',
    'bedroom': 'bed',
    'washroom': 'sink',
    'bathroom': 'sink',
    'kitchen': 'oven',
    'bar': 'counter',
    'spa': 'bed',
    'stair': 'stairs',
    'staircase': 'stairs',
    'step': 'stairs',
    'closet': 'shelving',
    'shelf': 'shelving',
    'bench': 'chair',
    'living': 'sofa',
    'shower': 'sink'
}

word_mapping = {
    'television': 'tv_monitor',
    'tv': 'tv_monitor',
    'equipment': 'gym_equipment',
    'gym': 'gym_equipment',
    'couch': 'sofa',
    'bedroom': 'bed',
    'washroom': 'sink',
    'bathroom': 'sink',
    'kitchen': 'sink',
    'barrier': 'door',
    'entrance': 'door',
    'vase': 'plant',
    'bar': 'counter',
    'spa': 'bed',
    'sauna': 'sink',
    'flower': 'plant',
    'stair': 'stairs',
    'staircase': 'stairs',
    'pool': 'chair',
    'photo': 'picture',
    'step': 'stairs',
    'seat': 'seating',
    'closet': 'shelving',
    'shelf': 'shelving',
    'fridge': 'appliances',
    'bench': 'chair'
}

semantic_sensor_40cat = {
    0: "wall",
    1: "floor",
    2: "chair",
    3: "door",
    4: "table",
    5: "picture",
    6: "cabinet",
    7: "cushion",
    8: "window",
    9: "sofa",
    10:"bed",
    11:"curtain",
    12:"drawer",
    13:"plant",
    14:"sink",
    15:"stairs",
    16:"ceiling",
    17:"toilet",
    18:"stool",
    19:"towel",
    20:"mirror",
    21:"tv_monitor",
    22:"shower",
    23:"column",
    24:"bathtub",
    25:"counter",
    26:"fireplace",
    27:"lighting",
    28:"beam",
    29:"railing",
    30:"shelving",
    31:"blinds",
    32:"gym_equipment",
    33:"seating",
    34:"board_panel",
    35:"furniture",
    36:"appliances",
    37:"clothes",
    38:"objects",
    39:"misc"
}

built_sem_labels = {0:'none', 1:'bag', 2:'bed', 3:'cabinet', 
    4:'ceiling', 5:'chair', 6:'clock', 7:'counter', 8:'curtain', 
    9:'door', 10:'fence', 11:'floor', 12:'keyboard', 13:'laptop', 14:'light', 
    15:'microwave', 16:'mirror', 17:'mouse', 18:'oven', 19:'pillow', 20:'plant', 
    21:'refrigerator', 22:'shelving', 23:'sink', 24:'sofa', 25:'stairs', 26:'table',
    27:'toaster', 28:'toilet', 29:'towel', 30:'tv', 31:'vase', 32:'wall', 33:'window'
}